/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register a new user */
        post: operations["register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login and receive auth cookies
         * @description On success, sets two HttpOnly cookies: `accessToken` (15 min) and `refreshToken` (7 days). Include `credentials: "include"` in fetch calls.
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Refresh the access token
         * @description Reads the `refreshToken` cookie and issues new auth cookies.
         */
        post: operations["refreshToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout and clear auth cookies */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current authenticated user */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all courses (instructor sees own, student sees enrolled) */
        get: operations["getCourses"];
        put?: never;
        /** Create a new course (instructor only) */
        post: operations["createCourse"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses/{courseId}/assistant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask the grounded Course Assistant
         * @description Retrieves only authorized material from the requested course. Students must be enrolled; instructors must own the course.
         */
        post: operations["askCourseAssistant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses/{courseId}/instructor-assistant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Ask the read-only Instructor Assistant for one course
         * @description Available only to the instructor who owns the requested course. The assistant can read course content and scoped operational statistics but cannot mutate data.
         */
        post: operations["askInstructorAssistant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a course by ID */
        get: operations["getCourse"];
        /** Update a course (instructor only) */
        put: operations["updateCourse"];
        post?: never;
        /** Delete a course (instructor only) */
        delete: operations["deleteCourse"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/enrollments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enroll in a course using enrollment code (student only) */
        post: operations["enroll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses/{courseId}/modules": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all modules for a course */
        get: operations["getModules"];
        put?: never;
        /** Create a module (instructor only) */
        post: operations["createModule"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/courses/{courseId}/modules/{moduleId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a module by ID */
        get: operations["getModule"];
        /** Update a module (owning instructor only) */
        put: operations["updateModule"];
        post?: never;
        /** Delete a module (owning instructor only) */
        delete: operations["deleteModule"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/modules/{moduleId}/lessons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all lessons for a module */
        get: operations["getLessons"];
        put?: never;
        /** Create a lesson (instructor only) */
        post: operations["createLesson"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/modules/{moduleId}/lessons/{lessonId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a lesson by ID */
        get: operations["getLesson"];
        /** Update or move a lesson (owning instructor only) */
        put: operations["updateLesson"];
        post?: never;
        /** Delete a lesson (owning instructor only) */
        delete: operations["deleteLesson"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/modules/{moduleId}/milestones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all milestones for a module */
        get: operations["getMilestones"];
        put?: never;
        /** Create a milestone (instructor only) */
        post: operations["createMilestone"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/milestones/{milestoneId}/lessons": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get all lessons linked to a milestone */
        get: operations["getMilestoneLessons"];
        put?: never;
        /** Link a lesson to a milestone (instructor only) */
        post: operations["addLessonToMilestone"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/milestones/{milestoneId}/lessons/{lessonId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a lesson from a milestone (instructor only) */
        delete: operations["removeLessonFromMilestone"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/milestones/{milestoneId}/submissions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get submissions for a milestone (instructor sees all, student sees own) */
        get: operations["getSubmissions"];
        put?: never;
        /** Submit a milestone (student only) */
        post: operations["createSubmission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/submissions/{id}/grade": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Grade a submission (instructor only) */
        post: operations["gradeSubmission"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/submissions/my/grades": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get the current student's graded submissions */
        get: operations["getMyGrades"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assistant/general": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask the General Assistant a platform question (authenticated users only) */
        post: operations["askGeneralAssistant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/modules/{moduleId}/lessons/{lessonId}/resources": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                moduleId: string;
                lessonId: string;
            };
            cookie?: never;
        };
        /** List lesson PDF resources */
        get: operations["listLessonResources"];
        put?: never;
        /** Upload a lesson PDF resource (owning instructor only) */
        post: operations["uploadLessonResource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/modules/{moduleId}/lessons/{lessonId}/resources/{resourceId}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Open or download an authorized lesson PDF */
        get: operations["downloadLessonResource"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/modules/{moduleId}/lessons/{lessonId}/resources/{resourceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete a lesson resource (owning instructor only) */
        delete: operations["deleteLessonResource"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/modules/{moduleId}/lessons/{lessonId}/resources/{resourceId}/reindex": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Retry lesson resource AI indexing (owning instructor only) */
        post: operations["reindexLessonResource"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/modules/{moduleId}/lessons/{lessonId}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate a lesson study summary from lesson text and all lesson PDFs */
        post: operations["generateLessonSummary"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterBody: {
            /**
             * Format: email
             * @example user@example.com
             */
            email: string;
            /**
             * @description Must contain at least one uppercase letter and one number
             * @example Password1
             */
            password: string;
            /** @example Jane Doe */
            name: string;
        };
        LoginBody: {
            /**
             * Format: email
             * @example user@example.com
             */
            email: string;
            /** @example Password1 */
            password: string;
        };
        User: {
            /**
             * Format: uuid
             * @example 123e4567-e89b-12d3-a456-426614174000
             */
            id?: string;
            /**
             * Format: email
             * @example user@example.com
             */
            email?: string;
            /** @example Jane Doe */
            name?: string;
            /**
             * @example student
             * @enum {string}
             */
            role?: "instructor" | "student";
            /**
             * Format: date-time
             * @example 2024-01-01T00:00:00.000Z
             */
            createdAt?: string;
            /**
             * Format: date-time
             * @example 2024-01-01T00:00:00.000Z
             */
            updatedAt?: string;
        };
        Course: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            instructorId?: string;
            /** @example Full Stack Bootcamp */
            title?: string;
            /** @example A complete bootcamp covering frontend and backend */
            description?: string;
            /**
             * @description Returned only to the instructor who owns the course
             * @example ABC123
             */
            enrollmentCode?: string;
            /** @example true */
            isPublished?: boolean;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        CreateCourseBody: {
            /** @example Full Stack Bootcamp */
            title: string;
            /** @example A complete bootcamp */
            description?: string;
            /** @example false */
            isPublished?: boolean;
        };
        CourseAssistantHistoryMessage: {
            /** @enum {string} */
            role: "user" | "assistant";
            content: string;
        };
        CourseAssistantRequest: {
            /** @example What is query invalidation? */
            message: string;
            history?: components["schemas"]["CourseAssistantHistoryMessage"][];
        };
        CourseAssistantSource: {
            /** @enum {string} */
            type: "lesson";
            /** Format: uuid */
            id?: string;
            title: string;
        };
        CourseAssistantMessage: {
            /** @enum {string} */
            type: "message";
            answer: string;
            sources: components["schemas"]["CourseAssistantSource"][];
        };
        InstructorAssistantSource: {
            /** @enum {string} */
            type: "lesson" | "milestone";
            /** Format: uuid */
            id: string;
            title: string;
        };
        InstructorAssistantMessage: {
            /** @enum {string} */
            type: "message";
            answer: string;
            sources: components["schemas"]["InstructorAssistantSource"][];
        };
        Module: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            courseId: string;
            /** @example Frontend Module */
            title: string;
            /** @example 1 */
            order: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        CreateModuleBody: {
            /** @example Frontend Module */
            title: string;
            /** @example 1 */
            order?: number;
        };
        UpdateModuleBody: {
            /** @example Frontend Module */
            title: string;
            /** @example 1 */
            order: number;
        };
        Lesson: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            moduleId: string;
            /** @example HTML Basics */
            title: string;
            /**
             * @example # HTML Basics
             *
             *     Learn the fundamentals of HTML...
             */
            content: string | null;
            /** @example https://youtube.com/embed/xyz */
            videoUrl: string | null;
            /** @example https://github.com/org/starter-repo */
            starterCodeUrl: string | null;
            /** @example 1 */
            order: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        CreateLessonBody: {
            /** @example HTML Basics */
            title: string;
            content?: string | null;
            videoUrl?: string | null;
            starterCodeUrl?: string | null;
            order?: number;
        };
        UpdateLessonBody: {
            /** @example HTML Basics */
            title: string;
            content: string | null;
            videoUrl: string | null;
            starterCodeUrl: string | null;
            order: number;
            /**
             * Format: uuid
             * @description Optional destination module. It must be in the same owned course.
             */
            moduleId?: string;
        };
        LessonResource: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            lessonId: string;
            title: string;
            originalFileName: string;
            /** @enum {string} */
            mimeType: "application/pdf";
            sizeBytes: number;
            /** @enum {string} */
            indexStatus: "pending" | "ready" | "failed";
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        LessonSummary: {
            /** @enum {string} */
            type: "summary";
            /** Format: uuid */
            lessonId: string;
            summary: string;
            sources: {
                /** @enum {string} */
                type: "lesson" | "resource";
                /** Format: uuid */
                id: string;
                title: string;
            }[];
        };
        Milestone: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            moduleId?: string;
            /** @example Build and Deploy a Responsive Landing Page */
            title?: string;
            /** @example Build a responsive landing page using HTML, CSS, and Flexbox */
            instructions?: string;
            /** @example Page must be responsive and deployed on Vercel */
            acceptanceCriteria?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        CreateMilestoneBody: {
            /** @example Build and Deploy a Responsive Landing Page */
            title: string;
            instructions?: string;
            acceptanceCriteria?: string;
        };
        Enrollment: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            studentId?: string;
            /** Format: uuid */
            courseId?: string;
            /** Format: date-time */
            enrolledAt?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        EnrollBody: {
            /** @example ABC123 */
            enrollmentCode: string;
        };
        SubmissionLink: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            submissionId?: string;
            /** @example https://github.com/student/project */
            url?: string;
            /**
             * @example github
             * @enum {string}
             */
            type?: "github" | "loom" | "deployment" | "other";
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        SubmissionLinkBody: {
            /** @example https://github.com/student/project */
            url: string;
            /**
             * @example github
             * @enum {string}
             */
            type: "github" | "loom" | "deployment" | "other";
        };
        SubmissionCourseSummary: {
            /** Format: uuid */
            id: string;
            title: string;
        };
        SubmissionModuleSummary: {
            /** Format: uuid */
            id: string;
            title: string;
            course?: components["schemas"]["SubmissionCourseSummary"];
        };
        SubmissionMilestoneSummary: {
            /** Format: uuid */
            id: string;
            title: string;
            module?: components["schemas"]["SubmissionModuleSummary"];
        };
        SubmissionStudent: {
            /** Format: uuid */
            id?: string;
            /** @example Alice Smith */
            name?: string;
            /**
             * Format: email
             * @example alice@example.com
             */
            email?: string;
        };
        Submission: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            milestoneId?: string;
            /** Format: uuid */
            studentId?: string;
            student?: components["schemas"]["SubmissionStudent"];
            /** Format: uuid */
            gradedBy?: string;
            /**
             * @example submitted
             * @enum {string}
             */
            status?: "draft" | "submitted" | "graded";
            /** @example 85 */
            score?: number;
            /** @example Great work! Clean code and well structured. */
            feedback?: string;
            links?: components["schemas"]["SubmissionLink"][];
            milestone?: components["schemas"]["SubmissionMilestoneSummary"];
            /** Format: date-time */
            submittedAt?: string;
            /** Format: date-time */
            gradedAt?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        CreateSubmissionBody: {
            links: components["schemas"]["SubmissionLinkBody"][];
        };
        GradeSubmissionBody: {
            /** @example 85 */
            score: number;
            /** @example Great work! */
            feedback?: string;
        };
        ErrorResponse: {
            /** @example Invalid credentials */
            error?: string;
        };
        MessageResponse: {
            data?: {
                /** @example Success */
                message?: string;
            };
        };
        ValidationErrorResponse: {
            /** @example Validation failed */
            error: string;
            errors: {
                /** @example email */
                field: string;
                /** @example Invalid email address */
                message: string;
            }[];
        };
        AssistantMessageBody: {
            /** @example How do I submit my milestone work? */
            message: string;
        };
        AssistantSource: {
            /**
             * @example policy
             * @enum {string}
             */
            type?: "policy" | "lesson" | "milestone";
            /** @example submission-rules */
            id?: string;
            /** @example Submission Rules */
            title?: string;
        };
        AssistantResponse: {
            /**
             * @example message
             * @enum {string}
             */
            type?: "message";
            /** @example You can submit via a GitHub, Loom, or Vercel link. */
            answer?: string;
            sources?: components["schemas"]["AssistantSource"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegisterBody"];
            };
        };
        responses: {
            /** @description User registered successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["User"];
                    };
                };
            };
            /** @description Email already in use */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginBody"];
            };
        };
        responses: {
            /** @description Login successful */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: {
                            user?: components["schemas"]["User"];
                        };
                    };
                };
            };
            /** @description Invalid credentials */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
        };
    };
    refreshToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Tokens refreshed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Missing or invalid refresh token */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out successfully */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["User"];
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getCourses: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of courses */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["Course"][];
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createCourse: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCourseBody"];
            };
        };
        responses: {
            /** @description Course created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["Course"];
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden - instructor only */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    askCourseAssistant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                courseId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CourseAssistantRequest"];
            };
        };
        responses: {
            /** @description A grounded answer or an insufficient-evidence message */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["CourseAssistantMessage"];
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Course enrollment or ownership required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Course not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidationErrorResponse"];
                };
            };
            /** @description Too many assistant requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The generation provider could not return a grounded answer */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Retrieval or generation is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    askInstructorAssistant: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                courseId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CourseAssistantRequest"];
            };
        };
        responses: {
            /** @description A course-scoped read-only instructor answer */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["InstructorAssistantMessage"];
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Instructor role and course ownership required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Course not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Validation failed */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too many assistant requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Tool selection or answer generation failed safely */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Course data, retrieval, or generation is unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getCourse: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Course details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["Course"];
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Course not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateCourse: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCourseBody"];
            };
        };
        responses: {
            /** @description Course updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["Course"];
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden - instructor only */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Course not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteCourse: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Course deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden - instructor only */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Course not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    enroll: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnrollBody"];
            };
        };
        responses: {
            /** @description Enrolled successfully */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["Enrollment"];
                    };
                };
            };
            /** @description Invalid enrollment code */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getModules: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                courseId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of modules */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["Module"][];
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createModule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                courseId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateModuleBody"];
            };
        };
        responses: {
            /** @description Module created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["Module"];
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden - instructor only */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getModule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                courseId: string;
                moduleId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Module details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["Module"];
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Module not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateModule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                courseId: string;
                moduleId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateModuleBody"];
            };
        };
        responses: {
            /** @description Module updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["Module"];
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Course ownership required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Module or course not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteModule: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                courseId: string;
                moduleId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Module deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Course ownership required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Module or course not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getLessons: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                moduleId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of lessons */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["Lesson"][];
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createLesson: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                moduleId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLessonBody"];
            };
        };
        responses: {
            /** @description Lesson created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["Lesson"];
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden - instructor only */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getLesson: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                moduleId: string;
                lessonId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lesson details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["Lesson"];
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Lesson not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    updateLesson: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                moduleId: string;
                lessonId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateLessonBody"];
            };
        };
        responses: {
            /** @description Lesson updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["Lesson"];
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Course ownership and same-course move required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Lesson, source module, or destination module not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteLesson: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                moduleId: string;
                lessonId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lesson deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Course ownership required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Lesson, module, or course not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getMilestones: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                moduleId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of milestones */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["Milestone"][];
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createMilestone: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                moduleId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMilestoneBody"];
            };
        };
        responses: {
            /** @description Milestone created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["Milestone"];
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden - instructor only */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getMilestoneLessons: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                milestoneId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of lessons linked to milestone */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["Lesson"][];
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    addLessonToMilestone: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                milestoneId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    lessonId: string;
                };
            };
        };
        responses: {
            /** @description Lesson linked to milestone */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: Record<string, never>;
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    removeLessonFromMilestone: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                milestoneId: string;
                lessonId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Lesson removed from milestone */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getSubmissions: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                milestoneId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List of submissions */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["Submission"][];
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createSubmission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                milestoneId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSubmissionBody"];
            };
        };
        responses: {
            /** @description Submission created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["Submission"];
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Published course enrollment required */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description The student already submitted this milestone */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    gradeSubmission: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GradeSubmissionBody"];
            };
        };
        responses: {
            /** @description Submission graded */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["Submission"];
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden - instructor only */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getMyGrades: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Student gradebook */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["Submission"][];
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden - student only */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    askGeneralAssistant: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssistantMessageBody"];
            };
        };
        responses: {
            /** @description Assistant answer */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["AssistantResponse"];
                    };
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Too many requests */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unexpected server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description AI provider error */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description AI service not configured */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listLessonResources: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                moduleId: string;
                lessonId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resource metadata only */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["LessonResource"][];
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Lesson not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    uploadLessonResource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                moduleId: string;
                lessonId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                    title?: string;
                };
            };
        };
        responses: {
            /** @description Uploaded resource metadata */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data: components["schemas"]["LessonResource"];
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid PDF or resource limit reached */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    downloadLessonResource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                moduleId: string;
                lessonId: string;
                resourceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description PDF bytes */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/pdf": string;
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    deleteLessonResource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                moduleId: string;
                lessonId: string;
                resourceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Resource deleted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MessageResponse"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    reindexLessonResource: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                moduleId: string;
                lessonId: string;
                resourceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Reindexed resource */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["LessonResource"];
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Resource not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description AI indexing unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    generateLessonSummary: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                moduleId: string;
                lessonId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Generated Markdown summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["LessonSummary"];
                    };
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Forbidden */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description No material or supported input bound exceeded */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description AI provider failure */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
